version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    container_name: rabbitmq
    ports:
      - "8080:15672"
      - "5672:5672"
      - "25676:25676"
    environment:
      RABBITMQ_DEFAULT_USER: cristiano
      RABBITMQ_DEFAULT_PASS: 123456789
    networks:
      - "rabbit_network"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 10s
      retries: 5
  # -----------------------------------------
  log-consumer:
    build: ./src/consumer/log
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - "rabbit_network"
    environment:
      CONNECTION_STRING: "amqp://cristiano:123456789@rabbitmq:5672"
networks:
  rabbit_network:
    driver: bridge
